# Generated by Django 6.0.3 on 2026-04-16 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество гостей",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveSmallIntegerField(
                unique=True, verbose_name="номер стола"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="seats",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="количество мест",
            ),
        ),
    ]
